# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-06-01 03:13
from __future__ import unicode_literals

import app01.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20200601_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='myfield',
            field=app01.models.MyCharField(max_length=16, null=True),
        ),
    ]
