# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-05-25 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20200525_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='info',
            field=models.CharField(max_length=32, null=True, verbose_name='个人简介'),
        ),
    ]
