# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-05-25 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_user_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hobby',
            field=models.CharField(default='study', max_length=32, verbose_name='兴趣爱好'),
        ),
    ]
